Jukebox UI update
AEFeinstein/Super-2024-Swadge-FW pull request #359
Opened 2024-12-31 06:15 UTC by Brycey92

### Description

I changed the background and font colors, and added music notes and clefs that float up from the bottom of the screen. They go faster when music is playing!

### Test Instructions

### Ticket Links

### Readiness Checklist
- [ ] I have run `make format` to format the changes
- [ ] I have compiled the firmware and the changes have no warnings
- [ ] I have compiled the emulator and the changes have no warnings
- [ ] I have run `make cppcheck` and checked that `cppcheck_result.txt` has no warnings for the changes
- [ ] I have added doxygen comments to any code used by more than one Swadge mode. This includes `/*! \file` comments with Design Philosophy, Usage, and Example sections for new headers.
- [ ] I have run `make docs` and checked that `doxy_warnings.txt` has no warnings for the new code

2024-12-31 10:32 UTC, AEFeinstein commented
[There were already some notes from the sequencer](https://github.com/AEFeinstein/Super-2024-Swadge-FW/tree/main/assets/sequencer/notes), but we've got enough space for both sets.

Also here's the list of MIDIs to load up (but maybe skip `menu/secret.mid`)
```
2048/Sounds/lullaby_in_numbers.mid
2048/Sounds/sndBounce.mid

bigbug/fromBreakout/brkBgmCrazy.mid
bigbug/fromBreakout/brkBgmFinale.mid
bigbug/fromBreakout/brkBgmPixel.mid
bigbug/fromBreakout/brkBgmSkill.mid
bigbug/fromBreakout/brkBgmTitle.mid
bigbug/fromBreakout/brkGameOver.mid
bigbug/fromBreakout/brkGetReady.mid
bigbug/fromBreakout/brkHighScore.mid
bigbug/fromBreakout/brkLvlClear.mid
bigbug/fromBreakout/sndBounce.mid
bigbug/fromBreakout/sndBreak2.mid
bigbug/fromBreakout/sndBreak3.mid
bigbug/fromBreakout/sndBreak.mid
bigbug/fromBreakout/sndBrk1up.mid
bigbug/fromBreakout/sndBrkDie.mid
bigbug/fromBreakout/sndDropBomb.mid
bigbug/fromBreakout/sndTally.mid
bigbug/fromBreakout/sndWaveBall.mid
bigbug/music/BigBug_Boss.mid
bigbug/music/BigBug_Dr.Garbotniks Home2.mid
bigbug/music/BigBug_Dr.Garbotniks Home.mid
bigbug/music/BigBugExploration.mid
bigbug/music/Big Bug Hurry up.mid
bigbug/music/BigBug_Space Travel.mid
bigbug/sounds/BigBug - Car 1.mid
bigbug/sounds/BigBug - Car 2.mid
bigbug/sounds/BigBug - Car 3.mid
bigbug/sounds/BigBug - Collection.mid
bigbug/sounds/BigBug - Egg 1.mid
bigbug/sounds/BigBug - Egg 2.mid
bigbug/sounds/Bump.mid
bigbug/sounds/Dirt_Breaking.mid
bigbug/sounds/Harpoon.mid
bigbug/sounds/r_health.mid
bigbug/sounds/r_item_get.mid
bigbug/sounds/r_p_ice.mid

cGrove/Audio/BGM/Chowa_Battle.mid
cGrove/Audio/BGM/Chowa_Dancing.mid
cGrove/Audio/BGM/Chowa_Meadow.mid
cGrove/Audio/BGM/Chowa_Menu.mid
cGrove/Audio/BGM/Chowa_Race.mid

credits/hd_credits.mid

jukebox/banana.mid
jukebox/Fairy_Fountain.mid
jukebox/Fauxrio_Kart.mid
jukebox/Follinesque.mid
jukebox/gamecube.mid
jukebox/hotrod.mid
jukebox/ode.mid
jukebox/pong/block1.mid
jukebox/pong/block2.mid
jukebox/pong/gmcc.mid
jukebox/stereo.mid
jukebox/yalikejazz.mid

menu/secret.mid

pango/sounds/bgmGameOver.mid
pango/sounds/bgmGameStart.mid
pango/sounds/Pango_Faster.mid
pango/sounds/Pango_Game Over.mid
pango/sounds/Pango_High Score.mid
pango/sounds/Pango_Jump Start.mid
pango/sounds/Pango_Level Clear.mid
pango/sounds/Pango_Main.mid
pango/sounds/Pango_Speed.mid
pango/sounds/snd1up.mid
pango/sounds/sndBlockCombo.mid
pango/sounds/sndBlockStop.mid
pango/sounds/sndDie.mid
pango/sounds/sndMenuConfirm.mid
pango/sounds/sndMenuDeny.mid
pango/sounds/sndMenuSelect.mid
pango/sounds/sndPause.mid
pango/sounds/sndSlide.mid
pango/sounds/sndSpawn.mid
pango/sounds/sndSquish.mid
pango/sounds/sndTally.mid

swadgeHero/songs/sh_bleed.mid
swadgeHero/songs/sh_cgrove.mid
swadgeHero/songs/sh_crace.mid
swadgeHero/songs/sh_credits.mid
swadgeHero/songs/sh_cremulons.mid
swadgeHero/songs/sh_devils.mid
swadgeHero/songs/sh_gs_credits.mid
swadgeHero/songs/sh_ocean.mid
swadgeHero/songs/sh_pain.mid
swadgeHero/songs/sh_pango.mid
swadgeHero/songs/sh_revenge.mid
swadgeHero/songs/sh_starfest.mid
swadgeHero/songs/sh_sunrise.mid
swadgeHero/songs/sh_wakeman.mid

test/stereo_test.mid

ultimateTTT/uttt_cursor.mid
ultimateTTT/uttt_marker.mid
ultimateTTT/uttt_win_g.mid
ultimateTTT/uttt_win_s.mid
```

2024-12-31 10:34 UTC, AEFeinstein commented on main/modes/music/jukebox/jukebox.c
> +    double y;
Usually I'd nitpick about `double` performance, but this is just a jukebox, not a game.

2025-01-01 10:57 UTC, AEFeinstein commented
Also, just so my intentions are clear, I'm going too wait until music is loaded up before merging here.

2025-01-01 10:59 UTC, AEFeinstein commented
Also the music list may be inaccurate shortly. Looks like bigbug removed some `fromBreakout` songs. Do your best, I'll do a double check before shipping.

2025-01-04 00:37 UTC, AEFeinstein commented on main/modes/games/2048/mode_2048.c
The `t48Mode` struct was already `extern`, so you could use `t48Mode.modeName` rather than `extern` the name itself.

2025-01-04 00:56 UTC, AEFeinstein commented on assets/bigbug/fromBreakout/sndBrkTally.mid
Looks like we used to have two `sndTally.mid`. Oops.

2025-01-04 01:01 UTC, AEFeinstein requested changes

2025-01-04 01:01 UTC, AEFeinstein commented on main/modes/music/jukebox/jukebox.c
> +        .name     = "Sunrise (Unused)",
You should `git merge origin/main` for this branch and make sure that all the referenced music is still there. I believe a bunch of `fromBreakout` stuff was removed.

2025-01-04 01:08 UTC, Brycey92 commented on main/modes/games/2048/mode_2048.c
Whoops! Want me to change it, or leave it for this year?

2025-01-04 01:34 UTC, Brycey92 commented on main/modes/music/jukebox/jukebox.c
> +        .name     = "Sunrise (Unused)",
Updated to match the new name and usage for `sh_sunrise.mid`, and removed the midis that were removed from `main`

2025-01-04 02:08 UTC, Brycey92 commented on main/modes/games/2048/mode_2048.c
Ah, GitHub for some reason didn't show your second message when I replied. Will leave it alone then 👍

2025-01-04 13:33 UTC, AEFeinstein commented
The jukebox sounds off, and I think it's because it's not using general midi. I did a search and the modes that call `midiGmOn()` are:
* system/intro
* system/credits
* system/mainMenu
* games/swadgeHero
* games/cGrove
* games/bigbug
* games/2048
* music/usbsynth
* music/tunernome
* music/sequencer
* test/factoryTest

I'm going to add a jukebox setting to use general midi for the appropriate modes

2025-01-04 14:28 UTC, AEFeinstein commented on main/modes/music/jukebox/jukebox.c
> +        .filename = "uttt_win_s.mid",
Tsk tsk tsk

2025-01-04 14:30 UTC, merged

2025-01-05 01:18 UTC, Brycey92 commented on main/modes/music/jukebox/jukebox.c
> +        .filename = "uttt_win_s.mid",
I have no idea how or when this and the pong typo got into the source, especially since the pong stuff should have been there from last year. Guess I'll go on a git blame marathon later to see when I introduced these. Either way, thanks for fixing them!

2025-01-05 01:18 UTC, Brycey92 commented
What's general midi?

2025-01-05 01:41 UTC, AEFeinstein commented
https://en.wikipedia.org/wiki/General_MIDI

2025-01-05 02:49 UTC, Brycey92 commented
Huh, neat! And it makes sense why that would cause newer MIDIs to sound off

![theMoreYouKnow2](https://github.com/user-attachments/assets/5783cb45-d043-488b-8010-0583bc1e5b20)